M.AutoInit();

data = {
    p: [
        {
            title: "MenuSmith",
            desc: "MenuSmith suggests recipes you can cook using the ingredients in your pantry.",
            link: "https://menusmith.com",
            img: "res/mandelbrot.jpg",
            tags: ["featured", "tools"],
            mobile: true,
            desktop: true
        },
        {
            title: "Mandelbrot Set",
            desc: "A JavaScript Mandelbrot Set explorer and animator.",
            link: "https://mandelbrot.andyhsmith.com",
            img: "res/mandelbrot.jpg",
            tags: ["featured", "artsy"],
            mobile: true,
            desktop: true
        },
        {
            title: "3D Wireframe",
            desc: "A custom 3D wireframe rendering using no external libraries.",
            link: "https://ideas.andyhsmith.com/custom/",
            img: "res/3dwireframe.png",
            tags: ["simulation"],
            mobile: false,
            desktop: true
        },
        {
            title: "Swarm Survivor",
            desc: "Survive waves of StarCraft Zerglings. How long can you last?",
            link: "https://unit.andyhsmith.com",
            img: "res/unit2.jpg",
            tags: ["unfinished"],
            mobile: true,
            desktop: true
        },
        {
            title: "Sierpinski's Triangle",
            desc: "Recursively draw the Sierpinski Triangle fractal.",
            link: "https://fractals.andyhsmith.com",
            img: "res/sierpinski.jpg",
            tags: ["artsy", "simulation"],
            mobile: true,
            desktop: true
        },
        {
            title: "Random TD",
            desc: "A tower defense game that is different every time you play.",
            link: "https://towerdefense.andyhsmith.com",
            img: "res/towerdefense.png",
            tags: ["unfinished"],
            mobile: false,
            desktop: true
        },
        {
            title: "Binary Rain",
            desc: "A fun graphical project that rains 1s and 0s.",
            link: "https://binaryrain.andyhsmith.com",
            img: "res/binaryrain.jpg",
            tags: ["simulation"],
            mobile: true,
            desktop: true
        },
        {
            title: "Youtube: Musical Neural Networks",
            desc: "Music generated by deep learning rrn neural networks.",
            link: "https://www.youtube.com/channel/UC67XdVlxmbCax9lcA3mlhGQ",
            img: "res/neurak.jpg",
            tags: ["featured", "artsy"],
            mobile: true,
            desktop: true
        },
        {
            title: "A.I. Rock Paper Scissors.",
            desc: "A.I. Rock Paper Scissors. A game that learns from your choices.",
            link: "https://rps.andyhsmith.com",
            img: "res/neurak.jpg",
            tags: ["game"],
            mobile: true,
            desktop: true
        },
        {
            title: "Bug Swarm",
            desc: "Control a swarm of bugs.",
            link: "https://bugs.andyhsmith.com",
            img: "res/neurak.jpg",
            tags: ["simulation"],
            mobile: true,
            desktop: true
        },
        {
            title: "Voxel World",
            desc: "Move and build in a 3D voxel world.",
            link: "https://voxel.andyhsmith.com",
            img: "res/neurak.jpg",
            tags: ["unfinished"],
            mobile: true,
            desktop: true
        }
    ]
}


function generateCard(obj) {
    let content = ""
    content += '<div class="card">'
    content +=      '<div class="card-image waves-effect waves-block waves-light">'
    content +=          '<img class="activator" src="' + obj.img + '">'
    content +=      '</div>'
    // content +=      '<div class="card-content">'
    // content +=          '<span class="card-title activator grey-text text-darken-4">' + obj.title + '<i class="material-icons right">more_vert</i></span>'
    // content +=      '</div>'
    content +=       '<div class="card-reveal"> <div class ="card-title" style=" width:100%; height: 100%; position:absolute;z-index: 1;"></div>' 
    content +=          '<span class="card-title grey-text text-darken-4">' + obj.title + '</span>'
    content +=          '<span>' + obj.desc + '</span>'
    content +=           '<br>'

    content +=           '<div style="position:absolute;left: 0px;bottom:0px;padding-left: 10px;"><a href="' + obj.link + '" style="color:steelblue; font-size: 20px;padding: 0px;" class="btn-flat waves-effect">Visit Site</a>'
    if (obj.mobile) {
        content +=      '<i class="fas fa-mobile"></i>'   
    }
    if (obj.desktop) {
        content +=      '<i class="fas fa-desktop"></i>' 
    }
    content +=      '</div></div>'
    content += '</div>'
    return content
}

function updateDOM() {
    let content = ""
    document.getElementById("featured-projects").innerHTML = ""
    document.getElementById("featured-projects-h").style.display = "none"
    if (tFeatured) {
        for (let i in data.p) {
            if (data.p[i].tags.includes("featured")) {
                content += generateCard(data.p[i])
            }
        }
        document.getElementById("featured-projects-h").style.display = "block"
        document.getElementById("featured-projects").innerHTML = content
    }
    
    document.getElementById("tools-projects").innerHTML = ""
    document.getElementById("tools-projects-h").style.display = "none"
    if (tTools) {
        content = ""
        for (let i in data.p) {
            if (data.p[i].tags.includes("tools")) {
                content += generateCard(data.p[i])
            }
        }
        document.getElementById("tools-projects-h").style.display = "block"
        document.getElementById("tools-projects").innerHTML = content
    }
    
    document.getElementById("artsy-projects").innerHTML = ""
    document.getElementById("artsy-projects-h").style.display = "none"
    if (tArtsy) {
        content = ""
        for (let i in data.p) {
            if (data.p[i].tags.includes("artsy")) {
                content += generateCard(data.p[i])
            }
        }
        document.getElementById("artsy-projects-h").style.display = "block"
        document.getElementById("artsy-projects").innerHTML = content
    }
    
    document.getElementById("game-projects").innerHTML = ""
    document.getElementById("game-projects-h").style.display = "none"
    if (tGames) {
        content = ""
        for (let i in data.p) {
            if (data.p[i].tags.includes("game")) {
                content += generateCard(data.p[i])
            }
        }
        document.getElementById("game-projects-h").style.display = "block"
        document.getElementById("game-projects").innerHTML = content
    }
    
    document.getElementById("simulation-projects").innerHTML = ""
    document.getElementById("simulation-projects-h").style.display = "none"
    if (tSim) {
        content = ""
        for (let i in data.p) {
            if (data.p[i].tags.includes("simulation")) {
                content += generateCard(data.p[i])
            }
        }
        document.getElementById("simulation-projects").innerHTML = content
        document.getElementById("simulation-projects-h").style.display = "block"
    }
    
    document.getElementById("unfinished-projects").innerHTML = ""
    document.getElementById("unfinished-projects-h").style.display = "none"
    if (tUnfinished) {
        content = ""
        for (let i in data.p) {
            if (data.p[i].tags.includes("unfinished")) {
                content += generateCard(data.p[i])
            }
        }
        document.getElementById("unfinished-projects").innerHTML = content
        document.getElementById("unfinished-projects-h").style.display = "block"
    }
}




var tFeatured = true
var tTools = true
var tArtsy = true
var tGames = true
var tSim = true
var tUnfinished = true
updateDOM()
function showAll() {
    console.log("all")
    tFeatured = true
    tTools = true
    tArtsy = true
    tGames = true
    tSim = true
    tUnfinished = true
    updateDOM()
}

function untoggle() {
    tFeatured = false
    tTools = false
    tArtsy = false
    tGames = false
    tSim = false
    tUnfinished = false
}

function show(id) {
    untoggle()
    if (id == 1) {
        tFeatured = true
    } else if (id == 2) {
        tTools = true
    } else if (id == 3) {
        tArtsy = true
    } else if (id == 4) {
        tGames = true
    } else if (id == 5) {
        tSim = true
    } else if (id == 6) {
        tUnfinished = true
    }

    updateDOM()
}


